#!/usr/bin/env bash
#
# Writes Config/Secrets.xcconfig from environment variables (used by CI and fastlane).
#
# Usage: scripts/write-secrets-xcconfig.sh [output-path]
#
# Environment (each may be empty or unset; empty values keep the app in its documented
# fallback, e.g. tokenless Storefront access):
#   KX_STOREFRONT_ACCESS_TOKEN      public Storefront API token of the Headless channel
#   KX_CUSTOMER_ACCOUNT_CLIENT_ID   Customer Account API public client ID
#   KX_APPLE_TEAM_ID                Apple Developer team ID (10 characters)
#
# Values are validated so that nothing can break out of the xcconfig syntax ("//" starts a
# comment there, newlines start a new setting). The values themselves are never printed.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
output="${1:-$repo_root/Config/Secrets.xcconfig}"

# name|allowed-characters-regex|human-readable rule
settings=(
    "KX_STOREFRONT_ACCESS_TOKEN|^[A-Za-z0-9_-]*$|letters, digits, '_' and '-'"
    "KX_CUSTOMER_ACCOUNT_CLIENT_ID|^[A-Za-z0-9_.-]*$|letters, digits, '_', '.' and '-'"
    "KX_APPLE_TEAM_ID|^([A-Z0-9]{10})?$|exactly 10 upper-case letters or digits"
)

lines=()
status=0
for setting in "${settings[@]}"; do
    IFS='|' read -r name pattern rule <<<"$setting"
    value="${!name:-}"
    # Tolerate surrounding whitespace from copy-pasted CI secrets.
    value="$(printf '%s' "$value" | tr -d '[:space:]')"
    if [[ ! "$value" =~ $pattern ]]; then
        echo "error: $name is invalid (expected $rule)." >&2
        status=1
        continue
    fi
    if [[ -n "$value" ]]; then
        lines+=("$name = $value")
        echo "$name: set"
    else
        lines+=("$name =")
        echo "$name: empty"
    fi
done

if [[ $status -ne 0 ]]; then
    exit "$status"
fi

mkdir -p "$(dirname "$output")"
umask 077
temporary="$(mktemp "$(dirname "$output")/.Secrets.xcconfig.XXXXXX")"
trap 'rm -f "$temporary"' EXIT
{
    echo "// Generated by scripts/write-secrets-xcconfig.sh. Do not commit (git-ignored)."
    printf '%s\n' "${lines[@]}"
} >"$temporary"
mv "$temporary" "$output"
trap - EXIT
echo "Wrote ${output#"$repo_root"/}"
